### ISSUE TITLE
Automatic session handling

### ISSUE THREAD

**Issue by Shukuyen** [piwik/piwik-sdk-ios#148]
I propose that we need automatic session handling in addition to the newly implemented manual session handling ( #136 ).

A session is defined in most tracking frameworks that I have previously worked with as 30 minutes. This seems to be the case for Piwik, too: https://piwik.org/faq/general/faq_36/

This means:
- Sessions should start automatically
- A new session should start automatically after 30 minutes
- We should be able to override the 30 minutes (preferably in the admin interface for the site, alternatively as a property on the Tracker shared instance)
- It is ok for users to be able to start a new session manually in code but this should not be necessary by default

**Comment by Shukuyen** [comment]
Label: swift3

**Comment by brototyp** [comment]
Hi @Shukuyen, thank you very much for your input! I just checked back with the Piwik Backend team and they ensured me that the documentation you mentioned [here](https://piwik.org/faq/general/faq_36/) should also be effective if you are using the iOS SDK. There is no need to add anything on the SDK or app side. The backend automatically starts a new visit, after 30 minutes is elapsed since the last view.

Please reopen this issue and get back to me if you encounter any issue.
