### ISSUE TITLE
on the README page link clearly to the Objective-C SDK 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-ios#165]
Hi @brototyp 
We got a user request asking for the objective-C SDK. Since we offer both, it would be great to add a clear link on the README to link to the "old" objective-C version of the SDK. This will give full flexibility to Piwik users. Thanks in advance!

**Comment by brototyp** [comment]
Hi @mattab, there is no additional version of the sdk under active development. We might list the version 3.x as implemented in Objective-C there but it will not get any new features (and supporting it will be pretty hard for me). In general the new SDK should be Objective-C compatible. The only downside is that one has to add the Swift runtime library.

What do you think about laying out these exact points in the README so the users can decide for themselves? I would like to move it to "Advanced" though since I think most users should use the Swift version.

**Comment by mattab** [comment]
Sounds good! 
I didn't know the new version was also compatible with Objective-C. That makes it easier. 

 * it would be useful to add a link to the older version, noting any limitations (not maintained, etc.). 
 * Also note in the README that the new version is compatible with both Objective-C and Swift

Thanks!

**Comment by mattab** [comment]
@brototyp If possible it would be great to include in the README,  a little example of how to use the Swift SDK with objective-C app? like a few lines showing that it is actually possible and how to initialise and call the SDK etc.

**Comment by brototyp** [comment]
@mattab The updated Readme just got merged and includes everything we discussed.

**Comment by mattab** [comment]
Thanks @brototyp for making this change, this will certainly help many users :+1:
