### ISSUE TITLE
Change iOS SDK license from MIT to BSD-3 

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-ios#212]
Hi @brototyp 

Currently most of our SDKs (Android, PHP, C#, Java...) are under BSD-3 license. iOS is the only SDK remaining under MIT license. For consistency it would be great to change the license of the project to BSD-3. The licenses are almost the same and it won't change anything for users or us, just be more consistent.

You can find the file here: https://github.com/piwik/piwik-sdk-android/blob/master/LICENSE

I think the only change needed is to update the LICENSE file in the project?

Thanks!

**Comment by brototyp** [comment]
Hi @mattab, imho changing the license in an open source project isn't that easy if there are multiple contributors. Every single contributor would have to have to give her/his permission since it is their code and they agreed to distribute it under the old license. See for example [this](https://opensource.stackexchange.com/questions/33/how-can-a-project-be-relicensed) thread.

**Comment by mattab** [comment]
Technically that's absolutely right, but since the license are almost the same and are fully compatible, and you contributed most of the code, I would not worry about it in this case, nobody would complain about it.

**Comment by brototyp** [comment]
Honestly I don't feel to good going this way. I value every little commit and I feel going this way would send the wrong kind of signal. If the "only" cause is consistency (which I am usually all in for) I would vote to postpone the License change until the next rewrite (that will eventually come 😊). Are you fine with that?

**Comment by mattab** [comment]
Sure it makes sense to wait for the next rewrite. it was only a suggestion :+1:

**Comment by brototyp** [comment]
Alright. Will close this for now.
