### ISSUE TITLE
When install MatomoTracker on objective-c project, I get more than 200 errors related to Mach-O

### ISSUE THREAD

**Issue by elkanaoptimove** [piwik/piwik-sdk-ios#250]
Hi,
I installed MatomoTracker through Cocoapods.
After I tried to build from the generated workspace, I was asked to specify swift version.
After that, I tried to build again and received more than 200 errors related to Mach-O
![screen shot 2018-05-29 at 18 57 07](https://user-images.githubusercontent.com/30383343/40670506-2292672e-6372-11e8-83b3-d5646abf73bf.png)

How can I fix this issue?

**Comment by brototyp** [comment]
Hi @elkanaoptimove, thanks for getting it touch. That is a very unfortunate issue you are having here. I guess the core issue is the "Auto-Linking library not found for ..." warnings up top. Can you give me some more information?

- Which Xcode version are you using?
- Which Swift version did you select? How did you "specify" it?

**Comment by elkorb** [comment]
@brototyp Hi,
I'm using xcode9.3 and swift version 4.1 was selected inside the Pods project
<img width="1064" alt="screen shot 2018-05-30 at 16 09 47" src="https://user-images.githubusercontent.com/4932580/40722050-f110d0a2-6423-11e8-8d9f-429dc87aff32.png">

**Comment by brototyp** [comment]
Hi @elkorb, thanks for your reply. Defining the Swift version there should not be necessary. Please try the following steps:

- Add a random .swift file to your project
- In you main target select the Swift version to 4.1
- perform a `pod install`

I hope that solves your issue.

**Comment by elkorb** [comment]
Working 😃😃😃.
Thanks.

**Comment by elkorb** [comment]
Working 😃😃😃.
Thanks a lot.

**Comment by brototyp** [comment]
Awesome! Thanks for the feedback. I guess we will update our guide on how to integrate the SDK into a project that has never seen a swift file before 😊

**Comment by flaushi** [comment]
I do have a similar problem. I cannot instantiate the matomoTracker 
![image](https://user-images.githubusercontent.com/15819451/41355495-f63f2ef8-6f21-11e8-9b5d-6e022f2e591a.png)

I did create a random swift file, and was asked if the bridging header should be created, what I answered with Yes.

I experience this problem since the last update (to xcode 9.4 or 9.3). Seems like the cocoapods integration or so has changed...?

The documentation [here](https://github.com/matomo-org/matomo-sdk-ios#objective-c-compatibility) confuses me as well, since it mentions version 4 of the SDK. However, the current version is 5.1.1. Should this be the origin of my problem such that I have to downgrade to v4?
Can u help please?

**Comment by brototyp** [comment]
Hi @flaushi, thanks for getting in touch.

About the documentation; Yes the version 4 there is misleading. It should state version for and higher, which it now does.

About your issue: Checking your screenshot it looks like there is a syntax error ("Expected ']'") in your file there. Please try and remove this init function and write it again. I guess there might be a non-visible character hiding there.

**Comment by flaushi** [comment]
Hey, thanks! You were right, after simply retyping my init function, everything is fine now. Thanks!
Viele Grüße,
Olli

**Comment by brototyp** [comment]
@flaushi Thanks for the feedback! Great to hear!
