### ISSUE TITLE
User ID uses "visitorId" in the doc

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-sdk-ios#258]
we noticed in the "User ID" readme that it says "matomoTracker.visitorId" (See: https://github.com/matomo-org/matomo-sdk-ios#custom-user-id)

-> would it be possible to also use "matomoTracker.userId" instead maybe for consistency?

**Comment by brototyp** [comment]
Hi @mattab, thanks for the hint and your suggestion 🙇.

Let's

* rename the `visitorId` property of the `MatomoTracker` to `userId`
* Update the README in this regard
* add a deprecated `visitorId` mapping to `userId` to the `MatomoTracker` with a proper deprecation message (we will keep this until the next major release of the SDK)

**Comment by mplackowski** [comment]
Hi, 

It would be great to have both parameters in the sdk. I mean the ("cid" and "uid" keys following this documentation: https://developer.matomo.org/api-reference/tracking-api)
In my usecase I need to setup visitorId ("cid" key ) manually after user converts from mobile website to the app. 

I'm using branch deeplinks with custom parameters and one of them is the pk_vid from the website. 
This way it is possible to track users switching from website to the app in a single visit (assuming that the same tracker is used on website and in the app). 

Being able to see user flow as a whole is a great feature, since the mobile website in many cases is the real starting point in the conversion funnel.

**Comment by brototyp** [comment]
@mplackowski I moved this to #259

**Comment by brototyp** [comment]
@mattab This got changed and will be part of the next release.

**Comment by mattab** [comment]
Thank you @brototyp :+1: so good to bring clarity and consistency wherever possible
