### ISSUE TITLE
Device Detection for Mac broken since 7.3

### ISSUE THREAD

**Issue by lrrrs** [piwik/piwik-sdk-ios#361]
I recently updated the Matomo SDK in my app to the latest version (7.3). Looking at the `operation system statistics`, more and more generic `Mac` systems w/o a detected version number popped up. I'm realizing now that it's completely broken since this change https://github.com/matomo-org/matomo-sdk-ios/pull/353.

A generated User-Agent from my Mac app looks like this:

`AppName/1.0 x86_64 macOS/11.0.1 MatomoTrackerSDK/7.3 Darwin/20.1.0`

And trying it out with the [device detector demo](https://devicedetector.lw1.at/AppName%2F1.0%20x86_64%20macOS%2F11.0.1%20MatomoTrackerSDK%2F7.3%20Darwin%2F20.1.0) confirms, that it's broken.

The old `User-Agent` generated from an earlier SDK version obviously works (But detects the OS wrong, it's 11.0 or 10.16 and not 10.15.6):

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) MatomoTracker SDK URLSessionDispatcher`

The question is: Should this be fixed in the client iOS/Mac SDK or on the server side? Help? 😊

**Comment by brototyp** [comment]
Hi @lrrrs, thanks for reporting this issue.

I just had a look at it. Apparently the old mechanism did report a macOS version that could be recognized, but it sometimes was wrong. [This](https://devicedetector.lw1.at/Mozilla%2F5.0%20(Macintosh;%20Intel%20Mac%20OS%20X%2010_15_6)%20AppleWebKit%2F605.1.15%20(KHTML,%20like%20Gecko)%20MatomoTracker%20SDK%20URLSessionDispatcher) for example is how the old version on 11.0.1 looks like (apparently webkit reports this wrong / differently).

For the issue you reported: I think the issue is the `macOS` I defined the OS name too. Looks like the detector only accepts `Mac OS X`. I'll create a PR in that regard. Do you mind having a look?

This is the PR: #362

**Comment by Findus23** [comment]
I guess Apple uses `Mac OS X` for historical reasons in their user agents and changing it would break a lot of things/sites.
But I think adding macOS to devicedetector wouldn't be unreasonable too. (but only fix this for future versions)

**Comment by lrrrs** [comment]
Yes, since 2016 it's called `macOS`, but to not break the whole internet I guess User-Agents in Safari, etc. are still reporting it as `Mac OS X`. Anyways. Thanks for the fix @brototyp. Just made a test using your branch and it can detect the version again.

**Comment by lrrrs** [comment]
I'm trying to do a quick temporary fix in the device detector. Would this be the right place (It does not seem to change anything):

`vendor/piwik/device-detector/regexes/oss.yml`

Add this rule:

```
- regex: 'macOS(?:[ /](?:Version )?(\d+(?:[_\.]\d+)+))?'
  name: 'Mac'
  version: '$1'
```

Testing it via Matomo > Diagnostics > Device Detection seems to work fine:

<img width="733" alt="Screen Shot 2020-11-16 at 12 08 05" src="https://user-images.githubusercontent.com/671002/99245801-7f8f2580-2804-11eb-8abe-63477207d1c9.png">
