### ISSUE TITLE
Not clear how to track events?

### ISSUE THREAD

**Issue by frogg** [piwik/piwik-sdk-ios#403]
I am using `self.matamoTracker?.track(event1)` to track an event.

I‘d expect to see the results online under "Behavior" –> "Events".
However, this page remains empty (date is set to today).

When I disable `isCustomAction`, they appear in the visits log, but all the custom variables are missing.
Is there any documentation how to use this API on iOS?

**Comment by frogg** [comment]
Has nobody else tried tracking events so far? 😯

**Comment by brototyp** [comment]
Hey @frogg, without seeing too much of your code, I would say it's correct.

If you can share an example application I can have a look at it. Otherwise have a look at the Example application where [events are tracked](https://github.com/matomo-org/matomo-sdk-ios/blob/develop/Example/ios/iOS%20Example/ScreenViewController.swift#L7).

The issue might be your custom variables. Did you [set them up](https://matomo.org/docs/custom-variables/) on the server side?

**Comment by brototyp** [comment]
I am closing this ticket for now. Please get in touch if this issue still exists.
