### ISSUE TITLE
Incorrect request URL?

### ISSUE THREAD

**Issue by AL1978** [piwik/piwik-sdk-ios#70]
From logs:  GET /piwik/piwik.php/?_cvar

The last "/" should be remove, I think.

**Comment by mattiaslevin** [comment]
Good comment.

The / is added by `AFHTTPSessionManager` in order support appending adding additional path components to the base url when building the request. Since the base URL already contains the full path nothing gets appended and the hence the trailing /.

Do not think it matters much but you are right.

Fixed by separating out the path when constructing the `AFHTTPSessionManager` and including it each time as path component when building the request.
