### ISSUE TITLE
Question: The auth_token has been removed for security reasons

### ISSUE THREAD

**Issue by nnblack1980** [piwik/piwik-sdk-ios#99]
I'm wondering if you could explain a bit about the auth_token and why it was removed in v3.0.0?

Also - without the token it would be great if you could explain how Piwik prevents anyone from writing false metrics into a site id based on the url?

Thanks in advance...

**Comment by brototyp** [comment]
@mattab Can you add some information to this question?

**Comment by mattab** [comment]
Hello, the issue is that when you set a `token_auth` in your mobile app (whether iOS or Android app), the token_auth will be easily found in the app binary. This means that any app user could find the token and as a result could mis-use it to call the Tracking API and do things that require special authentication (such as storing data for more than 24 hours in the past, etc. [see list here](http://developer.piwik.org/api-reference/tracking-api#other-parameters-require-authentication-via-token_auth))

As far as we know there was no secure way to put the token_auth in your apps without user being able to find them by decompiling etc. therefore the secure solution was to remove this feature. Hope it helps!
